[project]
name = "aiwolf-nlp-agent"
version = "0.1.0"
description = "aiwolf-nlp-agent"
license = { file = "LICENSE" }
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "aiwolf-nlp-common>=0.2.0",
    "bcrypt == 4.1.1",
    "certifi == 2023.7.22",
    "cffi == 1.16.0",
    "charset-normalizer == 3.2.0",
    "cryptography == 41.0.7",
    "idna == 3.4",
    "paramiko == 3.5",
    "pycparser == 2.22",
    "PyNaCl == 1.5.0",
    "requests == 2.31.0",
    "timeout-decorator == 0.5.0",
    "urllib3 == 2.0.5",
]
authors = [{ name = "aiwolf", email = "aiwolf@kanolab.net" }]
maintainers = [{ name = "aiwolf", email = "aiwolf@kanolab.net" }]
keywords = ["aiwolf"]

[project.urls]
Homepage = "https://aiwolf.org"
