permissions:
  contents: write

on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    if: github.repository == 'aiwolfdial/aiwolf-nlp-agent'
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "目次"